# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(473, 786)
        font = QtGui.QFont()
        font.setFamily("Hack")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 490, 61, 31))
        self.label.setObjectName("label")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setEnabled(True)
        self.sendButton.setGeometry(QtCore.QRect(370, 620, 91, 31))
        self.sendButton.setObjectName("sendButton")
        self.Output = QtWidgets.QTextBrowser(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(10, 690, 451, 41))
        self.Output.setObjectName("Output")
        self.megEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.megEdit.setGeometry(QtCore.QRect(10, 520, 451, 91))
        self.megEdit.setObjectName("megEdit")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(10, 620, 91, 31))
        self.exitButton.setObjectName("exitButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 81, 31))
        self.label_2.setObjectName("label_2")
        self.yourMeg = QtWidgets.QTextBrowser(self.centralwidget)
        self.yourMeg.setGeometry(QtCore.QRect(10, 50, 211, 431))
        self.yourMeg.setObjectName("yourMeg")
        self.otherMeg = QtWidgets.QTextBrowser(self.centralwidget)
        self.otherMeg.setGeometry(QtCore.QRect(240, 50, 221, 431))
        self.otherMeg.setObjectName("otherMeg")
        self.otherBox = QtWidgets.QComboBox(self.centralwidget)
        self.otherBox.setGeometry(QtCore.QRect(240, 10, 221, 32))
        self.otherBox.setCurrentText("")
        self.otherBox.setObjectName("otherBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 670, 58, 18))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.add = QtWidgets.QAction(MainWindow)
        self.add.setObjectName("add")
        self.rev = QtWidgets.QAction(MainWindow)
        self.rev.setObjectName("rev")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XChat"))
        self.label.setText(_translate("MainWindow", "Message:"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "You"))
        self.label_3.setText(_translate("MainWindow", "Output:"))
        self.add.setText(_translate("MainWindow", "Add friends"))
        self.rev.setText(_translate("MainWindow", "Del friends"))
